// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolySondage.Data;

namespace PolySondage.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211213143248_FirstMig")]
    partial class FirstMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PolySondage.Data.Models.Choice", b =>
                {
                    b.Property<int>("IdChoice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdPoll")
                        .HasColumnType("int");

                    b.Property<int?>("PollIdPoll")
                        .HasColumnType("int");

                    b.Property<int>("Vote")
                        .HasColumnType("int");

                    b.Property<int?>("VoteIdPoll")
                        .HasColumnType("int");

                    b.Property<int?>("VoteIdUser")
                        .HasColumnType("int");

                    b.HasKey("IdChoice");

                    b.HasIndex("PollIdPoll");

                    b.HasIndex("VoteIdPoll", "VoteIdUser");

                    b.ToTable("Choices");
                });

            modelBuilder.Entity("PolySondage.Data.Models.Poll", b =>
                {
                    b.Property<int>("IdPoll")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activate")
                        .HasColumnType("bit");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Unique")
                        .HasColumnType("bit");

                    b.Property<int?>("UserIdUser")
                        .HasColumnType("int");

                    b.HasKey("IdPoll");

                    b.HasIndex("UserIdUser");

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("PolySondage.Data.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PolySondage.Data.Models.Vote", b =>
                {
                    b.Property<int>("IdPoll")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.HasKey("IdPoll", "IdUser");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("PolySondage.Data.Models.Choice", b =>
                {
                    b.HasOne("PolySondage.Data.Models.Poll", null)
                        .WithMany("Choices")
                        .HasForeignKey("PollIdPoll");

                    b.HasOne("PolySondage.Data.Models.Vote", null)
                        .WithMany("Choices")
                        .HasForeignKey("VoteIdPoll", "VoteIdUser");
                });

            modelBuilder.Entity("PolySondage.Data.Models.Poll", b =>
                {
                    b.HasOne("PolySondage.Data.Models.User", null)
                        .WithMany("Created")
                        .HasForeignKey("UserIdUser");
                });

            modelBuilder.Entity("PolySondage.Data.Models.Poll", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("PolySondage.Data.Models.User", b =>
                {
                    b.Navigation("Created");
                });

            modelBuilder.Entity("PolySondage.Data.Models.Vote", b =>
                {
                    b.Navigation("Choices");
                });
#pragma warning restore 612, 618
        }
    }
}
